/**
 * Editorial intros for state directory pages. Each is 80–120 words of
 * original prose meant to add real human content to what is otherwise an
 * auto-generated listing page — improves AdSense quality assessment and
 * gives readers a reason to actually read the page.
 *
 * Keyed by state slug. Missing states fall back to the auto-generated
 * intro on the page (no editorial paragraph rendered).
 */
export const STATE_INTROS: Record<string, string> = {
  california:
    "California is where the modern American food-truck scene was invented. Roy Choi's Kogi BBQ in Los Angeles fused Korean and Mexican on a single tortilla in 2008 and the format hasn't looked back. The state spans every register — taco trucks in East LA that have been there for generations, ferment-and-foam fine-dining experiments in Oakland, fish-taco operations up and down the coast, and a Bay Area scene shaped by tech-worker lunches and pop-up culture. Permissive city regulations (especially in LA) and a year-round outdoor eating climate make California the country's deepest bench, by a wide margin.",

  texas:
    "Texas is the BBQ capital of the truck world and one of the country's most prolific Tex-Mex incubators. Austin's Central Texas-style brisket scene — post-oak smoke, salt-and-pepper rub, sliced to order on butcher paper — sets the bar for slow-smoked beef. Houston brings East Texas saucier ribs and a fierce Vietnamese bánh mì scene. San Antonio anchors South Texas barbacoa and breakfast-taco country. Dallas hosts a younger truck culture that mixes them all. Across the state, you'll find trucks that have run from the same lot for decades alongside week-one operators chasing the next great brisket. For a deeper breakdown, read our Texas BBQ guide.",

  'new-york':
    "New York's food truck scene is shaped by Manhattan's relentless lunch rush and the city's unmatched immigrant density. The halal cart — chicken or lamb over rice with white sauce — is a New York invention that has gone national. Taco trucks have taken over the Lower East Side and Chelsea, Indian kati-roll carts feed Midtown's office workers, and Brooklyn's Smorgasburg festival circuit has launched a generation of operators into national prominence. The space is brutal — permit caps, parking enforcement, weather — but the trucks that survive any of it tend to be very, very good. Read our local NYC guide for specific picks.",

  florida:
    "Florida's food truck scene is, like the state itself, three or four scenes pretending to be one. Miami is Cuban-and-Caribbean-forward — pressed sandwiches, ropa vieja bowls, mariquitas. Orlando's truck culture grew up around theme-park workers and runs late into the night. Tampa has a serious Cuban tradition rooted in Ybor City. Jacksonville and the Panhandle lean Southern and seafood-heavy. The whole state benefits from year-round outdoor eating weather and a constant influx of new operators trying their first menu on customers who can be charitable. Bring an appetite for fried things and a tolerance for humidity.",

  oregon:
    "Portland built the model of the food-truck pod — clusters of permanent trucks parked on a single lot, sharing seating and bathrooms, open year-round in defiance of the weather. The format works because Portland's regulations practically invited it and because the city's population takes food experiments seriously. You'll find Thai noodle operations that have been parked in the same spot for fifteen years next to week-old operators trying out fusion concepts. The trucks have collectively shaped Portland's reputation as one of the country's most adventurous food cities. The pods are concentrated downtown, in Northeast, and along Southeast Hawthorne.",

  tennessee:
    "Tennessee's food-truck scene is anchored by Nashville's white-hot hot-chicken trucks and Memphis's barbecue tradition — both regional dishes that have gone national in the last decade. Nashville's truck culture exploded as the city did, with operators experimenting alongside the hot-chicken explosion to figure out where the form ends. Memphis stays closer to the smokehouse tradition: dry-rubbed ribs, pulled pork shoulders, sticky pit-tomato sauce on the side. Knoxville and Chattanooga add scrappier scenes that pull from both poles. The whole state benefits from a long warm season and a permissive regulatory environment.",

  'new-jersey':
    "New Jersey's food truck scene runs on commuter density and an outsized Italian-American restaurant tradition. The Newark and Jersey City scenes are aggressive Portuguese, Brazilian, and Cuban — bringing a flavor of the diaspora to street level. The Princeton and Hoboken trucks lean upscale, often staffed by chefs who trained at New York restaurants and decamped across the river. South Jersey has a serious sub-and-cheesesteak culture that holds its own against Philly. New Jersey trucks tend to be unpretentious, generously portioned, and slightly less Instagram-friendly than their Manhattan counterparts. That's a feature, not a bug.",

  pennsylvania:
    "Pennsylvania's food trucks are mostly a Philadelphia and Pittsburgh story. Philly's cheesesteak truck tradition runs deep, but the more interesting action is in the city's halal carts, taco trucks, and Vietnamese bánh mì operators that feed the office workers around City Hall and the Penn campus. Pittsburgh's scene is younger and rougher around the edges — pierogi trucks, Polish-American comfort food, a serious BBQ contingent in the Strip District. State permitting is fragmented by city, which means each scene developed differently. The trucks tend to be solidly old-school in the best sense.",

  illinois:
    "Chicago's food truck scene exists in spite of itself. For years the city ran a 200-foot proximity rule that effectively banned trucks from operating near restaurants, which is most of the city. Recent reforms have loosened that, and the result is a scene that's young, hungry, and fiercely independent. Polish and Mexican operators dominate the established ranks; a new generation is bringing Korean, Filipino, and Ethiopian onto the street. Outside Chicago, the scene thins out fast — Springfield and the college towns have a few operators each, and that's roughly it.",

  georgia:
    "Atlanta's food truck scene punches well above the state's overall weight class. The city's Asian-American and African-American food cultures both show up on wheels in serious ways — Korean-fried-chicken trucks, soul-food trucks doing things that the brick-and-mortar restaurants don't dare, vegetarian operations running on a Sunday-supper cadence. Savannah's smaller scene leans coastal Southern (shrimp and grits, low-country boil), and Athens supports a college-driven truck culture that has produced a few breakout operators. State regulations are permissive enough to let operators experiment.",

  alabama:
    "Alabama's food trucks orbit around Birmingham, Huntsville, and Mobile — three cities with three very different appetites. Birmingham's scene leans toward elevated Southern, with operators who often came up through the city's white-tablecloth restaurants and decamped to lower-overhead trucks. Huntsville feeds aerospace workers serious lunches and runs an outsized number of barbecue and burger operators per capita. Mobile is Gulf-Coast through and through — fried seafood, gumbo, po' boys served from trailers that have done it the same way since long before food trucks were trendy. Across the state, the smoke is real and the portions are not symbolic.",

  alaska:
    "Alaska's food truck scene is more interesting than its weather should allow. Anchorage and Fairbanks both have small but serious year-round operations — Korean-Mexican fusion, halal carts catering to the city's growing immigrant communities, and a few salmon-and-reindeer-sausage trucks that lean into the local supply chain. The summer is short and the truck operators know it; the operators who survive run aggressive event schedules during the long-light months. What the Alaskan scene lacks in volume it makes up for in resilience and a captive audience that genuinely appreciates a hot meal served out a window.",

  arizona:
    "Arizona's truck scene is a story of Phoenix and Tucson, with the rest of the state thinning out fast. Phoenix's heat shapes everything — trucks operate aggressively at dawn and dusk, the menus lean lighter than you'd expect for the Southwest, and the cold-treat trucks (paletas, raspados, soft serve) anchor every food-truck event from April to October. Tucson's older Mexican-American food culture means the taco trucks here trend more traditional than in Phoenix, and the Sonoran hot dog — bacon-wrapped, mayo, beans, jalapeño salsa — is on more menus than you'd expect anywhere else in America.",

  arkansas:
    "Arkansas's food truck scene runs through Little Rock, Bentonville, and the Northwest Arkansas corridor that grew up around Walmart's headquarters. Little Rock's trucks lean classically Southern — barbecue, fried chicken, soul food — with a few new-wave Mexican and Vietnamese operators rounding out the lineup. Bentonville's scene is younger and reflects the rapid culinary growth that came with the Crystal Bridges museum and the corporate transplant population. The state's permissive vendor rules and low cost of starting a truck have kept the barrier to entry low; the result is a scene that punches above its national reputation.",

  colorado:
    "Colorado's truck scene is centered on Denver, Boulder, and the Front Range — heavily influenced by the state's outdoorsy lunch culture and the post-cannabis food economy. Denver's RiNo district has hosted some of the most ambitious operators in the Mountain West, with serious Mexican, Vietnamese, and Ethiopian trucks competing in a single block. Boulder leans health-forward and pricey; Colorado Springs leans military-friendly and portion-heavy. The state benefits from a strong year-round outdoor eating climate at altitude, and the trucks have collectively earned Denver a reputation as one of the country's better mid-size food cities.",

  connecticut:
    "Connecticut's truck scene is concentrated in Hartford, New Haven, and Stamford — close enough to NYC that the strongest operators sometimes commute to Manhattan for events, but distinct enough to have their own regional identity. New Haven brings its famous pizza tradition to a few mobile operators (rare; the brick ovens are the point). Hartford anchors a strong Puerto Rican and Dominican truck scene plus a respectable lobster-and-seafood lane. The state's small size makes it easy for trucks to chase events across multiple cities, and the regulatory environment is straightforward compared to its larger neighbors.",

  delaware:
    "Delaware's food truck scene is small, friendly, and surprisingly varied for a state with three counties. Wilmington has the highest concentration — corporate lunch crowds support a steady weekday operation of taco, halal, and barbecue trucks. Dover supports a smaller scene anchored by the air-base population and the state government. The summer beach towns (Rehoboth, Dewey) host seasonal trucks that print money for three months and disappear. The state's compact geography means a single truck can realistically cover Wilmington's lunch and Rehoboth's dinner in the same day. Many do.",

  hawaii:
    "Hawaii's food truck culture predates the modern American trend by decades — the plate-lunch wagon is a Hawaiian invention, and the format has spread to every island and almost every beach. Oahu's truck scene is the deepest: poke trucks, garlic shrimp wagons on the North Shore, Korean-Filipino-Japanese fusion operators in Honolulu, and the iconic shave-ice carts. Maui's truck culture is dominated by fish-taco and acai-bowl operations catering to tourists. The state's year-round eating climate and outdoor culture mean trucks operate as primary restaurants for many residents — these aren't side gigs, they're livelihoods.",

  idaho:
    "Idaho's food truck scene is anchored in Boise and the Treasure Valley, with smaller scenes in Idaho Falls and Coeur d'Alene. Boise has surprised people with its food culture growth over the last decade — a Basque heritage that shows up on a few trucks, plus the standard taco, burger, and barbecue lanes that any growing Western city develops. The Treasure Valley's permissive regulations have kept entry costs low, and Boise State games are reliable revenue drivers. The state's truck culture is small but earnest, and the operators tend to be year-round residents who've made deliberate choices about what to cook.",

  indiana:
    "Indiana's truck scene is split between Indianapolis and the college towns. Indianapolis runs a serious weekday lunch scene downtown, with trucks lining up around Monument Circle for the office crowd. Bloomington and Lafayette support student-driven late-night truck culture — gyros, halal, breakfast-burritos at 1am after a basketball game. South Bend has a small but loyal Polish-American truck lane reflecting the city's immigrant history. The state's truck regulations are reasonable and the climate supports a long enough season that operators can sustain a real business; the scene has grown noticeably in the last five years.",

  iowa:
    "Iowa's food truck scene is anchored by Des Moines and the Iowa City college town pull. Des Moines has emerged as a quietly serious food city — barbecue, tacos, halal, and a strong farm-to-truck lane that uses the state's agricultural identity to genuine effect. The Iowa State Fair gives operators a once-a-year cash machine that funds the rest of the year. Cedar Rapids and Davenport support smaller scenes; Iowa City's college rotation keeps a steady lunch and late-night demand. The state benefits from low barriers to truck startup and a customer base that respects portion size and value.",

  kansas:
    "Kansas's truck scene is split between Wichita, Kansas City (the Kansas side), and a Manhattan/college-town scene anchored by Kansas State. The Kansas City BBQ tradition extends across the border — burnt-end sandwich trucks are a regional specialty, and the operators who do them well move serious volume. Wichita's truck scene leans toward Southwestern Tex-Mex and a robust Vietnamese banh-mi presence that reflects the city's refugee community history. The state's barbecue scene gets less national press than Missouri's neighboring KC tradition, but the trucks operate at similar quality and lower prices.",

  kentucky:
    "Kentucky's food truck scene runs through Louisville and Lexington. Louisville's scene reflects the city's status as a food destination — serious Southern, strong Mexican, and a hot-brown-sandwich tradition that occasionally shows up on a truck even though the dish belongs in a restaurant. Lexington's truck culture grew up around the University of Kentucky and the horse-country event circuit. Kentucky bourbon distillery tours pull tourists who often discover their best meal of the trip at a truck parked nearby. The state's regulations are operator-friendly, and the truck startups are clustered around the urban corridors.",

  louisiana:
    "Louisiana's food truck scene is dominated by New Orleans, with Baton Rouge and Lafayette filling in. New Orleans is a fully serious food city — but the brick-and-mortar restaurants are so dominant that trucks often function as overflow venues for the city's best operators. The Cajun and Creole traditions show up in mobile form (gumbo trucks, po' boy operations, the occasional crawfish boil on wheels). Festival season — Jazz Fest, French Quarter Fest, dozens of smaller events — is when trucks make their money. The food is heavy, the season is long, and the standards are unforgiving.",

  maine:
    "Maine's truck scene is one of America's most underrated regional food cultures. Portland's truck and cart scene leans heavily toward seafood — lobster rolls (see our New England lobster roll trucks guide), fried clams, fish chowders — but also includes some of the most ambitious farm-to-truck operators in the country. The Bite Into Maine truck at Fort Williams Park is a destination in itself. Bangor and the smaller coastal towns support summer-only trucks that print money during tourist season. The state's short, intense summer is the operating window; the trucks that survive build their year around it.",

  maryland:
    "Maryland's food truck scene runs from Baltimore's crab-cake-and-pit-beef tradition through the DC suburbs' diverse weekday lunch crowd. Baltimore's truck culture leans gritty and unpretentious — Old Bay everything, pit beef sandwiches, the occasional crab cake on wheels (rare; the brick-and-mortars dominate). The DC-side suburbs (Silver Spring, Bethesda, College Park) support an aggressive multi-cuisine lunch scene that reflects the region's international population. Annapolis adds a summer seafood lane catering to sailing tourists. The state's regulations vary by county, which has created an uneven but generally vibrant scene.",

  massachusetts:
    "Massachusetts's truck scene is anchored by Boston and Cambridge, with the smaller Worcester and Springfield scenes filling in. Boston's truck culture is shaped by the city's universities — lunch trucks crowd around MIT, BU, and Northeastern on weekdays, and food-truck festivals draw serious crowds in summer. The state's seafood tradition shows up in lobster roll and clam shack operators, with the Connecticut and Maine lobster roll style debates playing out in real time on Cambridge sidewalks. Permitting is rigorous and expensive, which has filtered the operators down to a serious tier that knows what it's doing.",

  michigan:
    "Michigan's food truck scene runs through Detroit, Ann Arbor, and Grand Rapids — three very different cities that have each developed their own truck culture. Detroit's scene reflects the city's African-American and Middle Eastern populations: serious soul food and shawarma in roughly equal measure, plus a Coney-dog truck or two. Ann Arbor supports an academic and arts-influenced scene with the broadest cuisine range in the state. Grand Rapids has emerged as a quietly serious West Michigan food city. The state's truck regulations are reasonable, and the summer event circuit gives operators reliable revenue from May through October.",

  minnesota:
    "Minnesota's truck scene is centered on the Minneapolis–St. Paul Twin Cities, with the State Fair as the annual cash machine. The Twin Cities' truck culture reflects the area's immigrant communities — strong Somali (sambusa and hilib), Hmong, and Vietnamese operators, plus the standard barbecue, tacos, and burgers. Minneapolis hosts some of the country's most ambitious food-truck events during summer; St. Paul's scene runs slightly more residential. The Minnesota State Fair in late August is the financial event of the year for any truck that lands a slot; operators plan their winter around it. Northern Minnesota's scene is seasonal but real.",

  mississippi:
    "Mississippi's food truck scene is small but earnest. Jackson, the Coast, and Oxford anchor the three pockets. Jackson's trucks lean classically Southern with a strong barbecue and soul-food presence. The Gulf Coast (Biloxi, Gulfport, Bay St. Louis) hosts seafood operators serving po' boys, fried shrimp, and oyster baskets — the post-Katrina rebuild has produced a quietly excellent regional truck culture. Oxford's truck scene is shaped by the University of Mississippi and SEC football season — the Grove tailgating events draw serious operators. The state's regulations are loose and the entry costs are low; trucks proliferate easily.",

  missouri:
    "Missouri's truck scene runs through Kansas City and St. Louis — two cities with two very different food cultures. Kansas City is barbecue country: burnt ends, ribs, the classic KC-style sweet sauce, and trucks that have been doing it for decades. St. Louis brings a more European base — Italian, German, and an outsized Vietnamese banh-mi presence in South City. The Lake of the Ozarks summer scene supports a seasonal truck circuit catering to vacation crowds. Columbia and Springfield support college and family-friendly scenes respectively. The state's regulations are reasonable and the barbecue trucks alone justify a road trip.",

  montana:
    "Montana's truck scene is small, scrappy, and seasonal. Billings, Bozeman, and Missoula anchor the major scenes; the rest of the state has a few trucks each. Bozeman's growth has produced the most diverse scene — the influx of Pacific Northwest transplants has brought Vietnamese, Korean, and Mexican trucks to a town that didn't have them ten years ago. Missoula's scene leans toward farm-to-truck operators leveraging the state's ranching tradition. Billings is the most traditional — beef-heavy, BBQ-friendly. The short summer is the operating season; the operators who survive winter run aggressive event schedules in the warm months.",

  nebraska:
    "Nebraska's food truck scene is centered on Omaha and Lincoln. Omaha's truck culture grew up around the city's steakhouses and meat-packing history — many trucks lean into beef in serious ways, with brisket and burnt-end operators rivaling neighboring Kansas City. Lincoln's scene is shaped by the University of Nebraska and Husker football — the tailgating market alone supports several full-time operators. The state's Vietnamese and Mexican communities show up on trucks reflecting the meatpacking immigration history. Regulations are reasonable; the operating season runs March through November; the state's truck culture is quietly more interesting than its national reputation suggests.",

  nevada:
    "Nevada's truck scene is dominated by Las Vegas, with Reno, Henderson, and Carson City rounding out the picture. Vegas's truck culture is uniquely shaped by 24-hour operations and the convention/event circuit — many trucks operate primarily as private catering for trade shows and weddings, with public service as a marketing arm. The taco trucks east of the Strip serve a heavily Mexican-American population and are some of the best in the Southwest. Reno's smaller scene leans more toward burger-and-BBQ trucks catering to the casino tourist crowd. Nevada's regulations are operator-friendly and the year-round eating climate (though hot) supports continuous operation.",

  'new-hampshire':
    "New Hampshire's truck scene is small, friendly, and concentrated in Manchester, Portsmouth, and the seacoast. Manchester anchors the year-round operations — barbecue, tacos, the occasional New England seafood roll. Portsmouth's smaller scene takes advantage of the historic-tourism crowd and the summer beach traffic. Concord supports a modest state-capital lunch scene. The state's permissive regulations and proximity to Boston (without the Boston rents) have made New Hampshire an attractive launchpad for trucks; several Boston-area operators run a NH location for the lower overhead. The lobster roll and clam-shack tradition shows up on trucks at the seacoast.",

  'new-mexico':
    "New Mexico's truck scene runs through Albuquerque and Santa Fe, with the state's distinctive cuisine appearing in both classical and crossover form. The red/green chile divide is in full effect — most trucks default to a red chile or green chile drizzle on every protein, and customers expect to be asked. Albuquerque's scene leans more populist; Santa Fe trends upscale with farm-to-truck operators using the state's strong agricultural identity. The breakfast burrito truck is a New Mexico institution. The state's truck regulations are friendly and the dry, mild climate supports year-round operation. The food is hotter than anywhere outside Louisiana.",

  'north-carolina':
    "North Carolina's truck scene is anchored by Charlotte, Raleigh-Durham, and Asheville — three cities with three distinct food cultures. Charlotte's banking-and-corporate lunch crowd supports a serious weekday operation across cuisines. The Raleigh-Durham Research Triangle hosts an academic crowd and one of the country's most diverse mid-size truck scenes. Asheville's truck culture leans new-American, farm-to-truck, occasionally weird in a good way — the city's small but serious food reputation extends to its trucks. Eastern NC barbecue (whole-hog, vinegar-based) shows up on a few specialist trucks. The state's truck regulations are reasonable across most counties.",

  'north-dakota':
    "North Dakota's truck scene is anchored in Fargo and Bismarck, with a few summer-seasonal operations in the oil patch. Fargo's scene has grown noticeably with the city's tech and university expansion — there are now serious taco, Mexican, and Vietnamese operators where there were almost none a decade ago. Bismarck's scene leans more traditional with barbecue and burger trucks dominating. The oil patch trucks (Williston, Watford City) serve a captive worker audience at premium prices for huge portions. The short Northern Plains summer is the operating season; the operators who survive run aggressive event schedules from May through September.",

  ohio:
    "Ohio's truck scene runs through Cleveland, Cincinnati, Columbus, and the smaller industrial cities. Cleveland's scene reflects its Eastern European immigrant history — pierogi trucks, kielbasa operators, plus the standard taco and burger lanes. Cincinnati's truck culture trends toward the city's German heritage and its unique chili tradition (the famous Cincinnati chili shows up on a few trucks, with predictable controversy). Columbus has emerged as the most diverse and adventurous truck city in the state, driven by the OSU student population and a growing immigrant community. The state's regulations vary by city and county; Columbus is friendliest.",

  oklahoma:
    "Oklahoma's truck scene is anchored by Oklahoma City and Tulsa, with strong Mexican-American and Vietnamese operators reflecting the state's immigration history. OKC's scene has grown alongside the city's downtown revitalization — taco trucks, banh-mi operations, BBQ and steak-driven trucks reflecting the cattle country tradition. Tulsa's truck culture leans more food-festival-friendly and supports a serious arts-district scene. The state's barbecue tradition shows up on trucks with a slightly sweeter sauce and broader meat selection than Texas — beef brisket alongside chopped pork and bologna. The state's regulations are loose and the operating season runs March through November.",

  'rhode-island':
    "Rhode Island's truck scene is small (it's a small state) but serious. Providence anchors the major operations — coffee milk and stuffies on a few specialist trucks, plus the standard Italian-American tradition that reflects Providence's heritage. Newport's summer scene is high-volume and tourist-driven; the seafood operators here include some of New England's best lobster-and-clam shack trucks (see our New England lobster roll guide). Warwick supports a steady weekday lunch scene. The state's permissive truck regulations and dense population make Rhode Island one of the higher trucks-per-capita states in the country.",

  'south-carolina':
    "South Carolina's truck scene runs through Charleston, Columbia, and Greenville. Charleston's truck culture has grown alongside the city's broader food destination status — serious Lowcountry cuisine on wheels (shrimp and grits, she-crab soup, frogmore stew variations), plus a steady supply of barbecue trucks. Columbia's State House and USC support a weekday lunch scene. Greenville has emerged as a quietly serious upstate food city with an active truck culture. South Carolina barbecue (the mustard-based sauce, the whole-hog tradition) shows up on specialist trucks. The summer is hot but long; the operating season is essentially year-round.",

  'south-dakota':
    "South Dakota's truck scene is anchored in Sioux Falls and Rapid City, with seasonal Black Hills tourism filling in the western half. Sioux Falls's growth in the last decade has produced a surprising number of new trucks — Mexican, halal, BBQ, plus the expected American lanes. Rapid City and the Black Hills run hard during Sturgis Motorcycle Rally and the summer tourist season; trucks that lock in slots near Mount Rushmore make their year in three months. The state's regulations are loose and the cost of entry is among the lowest in the country. The trucks tend to be year-round local operators rather than seasonal pop-ups.",

  utah:
    "Utah's truck scene is anchored by Salt Lake City, Provo, and Park City. SLC's truck culture has grown alongside the city's increasingly diverse food scene — Mexican, Vietnamese, halal, and a strong Polynesian truck presence reflecting the LDS-Polynesian community connection. Provo's truck scene is BYU-driven and family-friendly. Park City's seasonal operators run during ski and summer tourism windows. The state's regulations are reasonable, the climate supports year-round operation with a slight winter slowdown, and the trucks have collectively pushed SLC into the conversation as one of the better mid-size food cities in the Mountain West.",

  vermont:
    "Vermont's truck scene is small, friendly, and almost entirely concentrated in Burlington. Burlington's truck culture leans heavily toward farm-to-truck operators using the state's strong agricultural identity — local cheese, grass-fed beef, maple-everything, a serious Vietnamese banh-mi operator or two. Montpelier supports a small state-capital lunch scene. The summer is the operating window; many operators close December through March. The state's regulations are loose and the operators tend to be deeply connected to local farms. Trucks here are often as much about the sourcing as the cooking, which produces a slightly different (and slightly more expensive) food than you'd find in larger cities.",

  virginia:
    "Virginia's truck scene runs from the Washington DC suburbs through Richmond and Norfolk. Northern Virginia (Arlington, Alexandria) supports a serious weekday lunch scene that reflects the federal-worker population and Pentagon-adjacent corporate density. Richmond has emerged as a food destination in its own right, with strong fried-chicken, BBQ, and globally diverse truck operators clustered around the Fan and downtown. The Hampton Roads area (Norfolk, Virginia Beach) hosts a Navy-influenced scene with strong Filipino and Korean operators. Virginia's regulations vary by county; Northern Virginia is friendliest.",

  washington:
    "Washington's truck scene is anchored by Seattle, with Spokane and Tacoma filling in. Seattle's truck culture grew up around the city's strong coffee tradition and tech-worker lunch crowds — espresso carts are technically food trucks too, and Seattle has more of them per capita than anywhere in America. The food trucks proper trend toward Asian-fusion (pho, banh mi, Korean BBQ, Thai), with strong Mexican and BBQ representation. Spokane's smaller scene leans American comfort food. Washington's regulations are reasonable and the year-round (if rainy) climate supports continuous operation. The seafood and Asian cuisine concentration makes Seattle's trucks worth seeking out.",

  'west-virginia':
    "West Virginia's truck scene is small but earnest. Charleston (the WV capital, not the SC city) anchors the year-round scene with barbecue, comfort food, and a quietly serious Italian-American truck presence reflecting the state's Italian immigration history. Morgantown's scene runs on West Virginia University's student population — late-night burgers, breakfast trucks, the occasional weird specialty operation. The state's regulations are loose and the cost of entry is among the lowest in the country. The trucks here tend to be small family operations that have served the same towns for years, with portions generous enough to forgive a few rough edges on the menu.",

  wisconsin:
    "Wisconsin's truck scene runs through Milwaukee and Madison, with the State Fair and football tailgating filling the rest of the calendar. Milwaukee's truck culture reflects the city's German, Polish, and Mexican heritage in roughly equal measure — sausage trucks alongside taco operators alongside Polish-style trucks. Madison's truck scene is shaped by the University of Wisconsin and the State Capitol's lunch crowd; the diversity is high and the standards are higher than you'd expect for the Midwest. Green Bay's seasonal Packers tailgating supports a major game-day truck circuit. The state's cheese tradition shows up on trucks in ways that other states should envy.",

  wyoming:
    "Wyoming's truck scene is sparse but determined. Cheyenne and Casper anchor the year-round operations, and Jackson Hole hosts a serious seasonal tourist-truck circuit during ski season and summer national park traffic. Cheyenne's truck culture leans American comfort food with strong barbecue and burger representation; the state's cattle country shows up in beef-heavy menus. Jackson's seasonal trucks operate at near-resort prices and quality, taking advantage of the captive tourist audience. The state's regulations are loose and the operating season is short outside the major tourist zones. Trucks here are usually year-round residents serving local communities, not gig operators.",
};
